package io.github.tuguzt.pcbuilder.domain.model

import io.github.tuguzt.pcbuilder.domain.interactor.randomNanoId
import kotlinx.serialization.Serializable

/**
 * NanoID generated by [randomNanoId] function.
 */
@JvmInline
@Serializable
public value class NanoId(private val value: String) {
    override fun toString(): String = value
}
