package io.github.tuguzt.pcbuilder.domain.model

import io.github.tuguzt.pcbuilder.domain.randomNanoId
import kotlinx.serialization.Serializable

/**
 * NanoID generated by [randomNanoId] function.
 */
@JvmInline
@Serializable
public value class NanoId(private val value: String) : Comparable<NanoId> {
    override fun compareTo(other: NanoId): Int = value.compareTo(other.value)

    override fun toString(): String = value
}
